package ua.tqs.airquality;
// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;

// import static org.junit.jupiter.api.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

// @ExtendWith(SeleniumJupiter.class)
public class WebInterfaceTest {

    /*
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        // this.driver = driver;
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void hw() {
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(924, 1053));
        driver.findElement(By.cssSelector(".container")).click();
        // dunno if right module
        assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Select your location:"));
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.id("dropdownMenuButton")).click();
        driver.findElement(By.id("finland/lohja/harjula")).click();
        driver.findElement(By.cssSelector(".container")).click();
        // assertThat(driver.findElement(By.cssSelector("b > span")).getText(), is("Harjula, Lohja, Finland"));
        // assertThat(driver.findElement(By.xpath("xpath=//div[@id='frag']/p/u/b/span")).getText(), is("Harjula, Lohja, Finland"));
        driver.findElement(By.id("frag")).click();
        driver.findElement(By.id("dropdownMenuButton")).click();
        driver.findElement(By.id("helsinki")).click();
        driver.findElement(By.cssSelector("u")).click();
        driver.findElement(By.cssSelector("u")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("u"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("u")).click();
        assertThat(driver.findElement(By.cssSelector("u")).getText(), is("Showing results for Helsinki"));
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).click();
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).click();
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).click();
        assertThat(driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(2)")).getText(), is("Avg"));
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)")).click();
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)")).click();
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)")).click();
        assertThat(driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(3)")).getText(), is("Min"));
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(4)")).click();
        driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(4)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(4)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        assertThat(driver.findElement(By.cssSelector("div:nth-child(3) > .table th:nth-child(4)")).getText(), is("Max"));
        driver.findElement(By.cssSelector(".dropdown")).click();
    }

     */
}
